### ISSUE TITLE
No inscription?

### ISSUE THREAD

**Issue by Ranakastrasz** [brianfaires/crawl-rc#1]
I tested the allRC.txt as an Init, and while it mostly worked, no item seemed to receive inscriptions. I am uncertain if there is a step I am missing.

**Comment by Ranakastrasz** [comment]
Rereading front page shows this is a known issue. Admittedly, i am unsure why you wrote code for an unsupported feature

**Comment by brianfaires** [comment]
I've written the supporting code for inscriptions but waiting on the
regular devs to pull it into the main code.  You'd only need
runrest-features.rc though, and the section of init.txt marked "Lua hook
functions". None of that uses inscriptions.  No worries if it's more
trouble than it's worth though - just sharing what I've got.
