### ISSUE TITLE
After Berserk, Rest doesn't get interupted by Combat

### ISSUE THREAD

**Issue by Ranakastrasz** [brianfaires/crawl-rc#2]
The "ready_fully_recover" function, if you have berserked, are now slowed and -berserk, will, when you use the "5" hotkey to fully rest, will not be interrupted in the case of a monster showing up, resulting in you waiting until you, usually, die.

**Comment by brianfaires** [comment]
This is already fixed. Using CMD_SAFE_WAIT instead of CMD_WAIT.

**Comment by brianfaires** [comment]
I appreciate the report though! This thing is def a work in progress
